/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.dialogs;

import database.ConnectionProvider;
import errorChecking.InputCheck;
import inventorydatabase.Account;
import inventorydatabase.Person;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Joseph
 */
public class NewAccount extends javax.swing.JDialog {

    private List<Person> people = new ArrayList();
    private List<Account> accounts = new ArrayList();
    /**
     * Creates new form NewAccount
     */
    public NewAccount(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fillPeople();
        fillAccounts();
        setLocationRelativeTo(null);
        setTitle("Registering new account");
        setResizable(false);
        setVisible(true);
        
    }
    
    private void fillPeople(){
        ConnectionProvider conn = new ConnectionProvider();
        people = conn.getPeople();
        System.out.println(people.size());
    }
    
    private void fillAccounts(){
        ConnectionProvider conn = new ConnectionProvider();
        accounts = conn.getAccounts();
        System.out.println(accounts.size());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtPassword1 = new javax.swing.JPasswordField();
        txtPassword2 = new javax.swing.JPasswordField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtCardID = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblLoginWarning = new javax.swing.JLabel();
        lblPassword1Warning = new javax.swing.JLabel();
        lblPassword2Warning = new javax.swing.JLabel();
        lblFirstNameWarning = new javax.swing.JLabel();
        lblLastNameWarning = new javax.swing.JLabel();
        lblCardIDWarning = new javax.swing.JLabel();
        lblEmailWarning = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Login: ");

        jLabel2.setText("Password: ");

        jLabel3.setText("Repeat password: ");

        jLabel4.setText("First name: ");

        jLabel5.setText("Last name:");

        jLabel6.setText("Card ID:");

        jLabel7.setText("Email:");

        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLoginKeyTyped(evt);
            }
        });

        txtPassword1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassword1KeyTyped(evt);
            }
        });

        txtPassword2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassword2KeyTyped(evt);
            }
        });

        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyTyped(evt);
            }
        });

        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLastNameKeyTyped(evt);
            }
        });

        txtCardID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCardIDKeyTyped(evt);
            }
        });

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        lblLoginWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblLoginWarning.setText(" ");

        lblPassword1Warning.setForeground(new java.awt.Color(255, 0, 0));
        lblPassword1Warning.setText(" ");

        lblPassword2Warning.setForeground(new java.awt.Color(255, 0, 0));
        lblPassword2Warning.setText(" ");

        lblFirstNameWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblFirstNameWarning.setText(" ");

        lblLastNameWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblLastNameWarning.setText(" ");

        lblCardIDWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblCardIDWarning.setText(" ");

        lblEmailWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblEmailWarning.setText(" ");

        btnConfirm.setText("Confirm");
        btnConfirm.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnConfirm.setMaximumSize(new java.awt.Dimension(70, 23));
        btnConfirm.setMinimumSize(new java.awt.Dimension(70, 23));
        btnConfirm.setPreferredSize(new java.awt.Dimension(70, 23));
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnCancel.setMaximumSize(new java.awt.Dimension(70, 23));
        btnCancel.setMinimumSize(new java.awt.Dimension(70, 23));
        btnCancel.setPreferredSize(new java.awt.Dimension(70, 23));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCardID, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmailWarning)
                            .addComponent(lblCardIDWarning)
                            .addComponent(lblLastNameWarning)
                            .addComponent(lblFirstNameWarning)
                            .addComponent(lblPassword2Warning)
                            .addComponent(lblPassword1Warning)
                            .addComponent(lblLoginWarning))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoginWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPassword1Warning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPassword2Warning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFirstNameWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLastNameWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCardID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCardIDWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmailWarning)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtLoginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyTyped
        if(txtLogin.getText().length() >= 20){
            evt.consume();
        }
    }//GEN-LAST:event_txtLoginKeyTyped

    private void txtPassword1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassword1KeyTyped
        if(txtPassword1.getPassword().length >= 20){
            evt.consume();
        }
    }//GEN-LAST:event_txtPassword1KeyTyped

    private boolean isLoginInUse(String login){
        for(Account acc : accounts){
            if((acc.getLogin()).equalsIgnoreCase(login)){
                return true;
            }
        }
        return false;
    }
    
    private boolean isCardIDinUse(String cardID){
        for(Person person : people){
            if((person.getCardId()).equalsIgnoreCase(cardID)){
                return true;
            }
        }
        return false;
    }
    
    
    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        InputCheck inputCheck = new InputCheck();
        int[] correctInputs = new int[7];
        String login = txtLogin.getText().trim();
        String password1 = new String(txtPassword1.getPassword());
        String password2 = new String(txtPassword2.getPassword());
        String firstName = txtFirstName.getText().trim();
        String lastName = txtLastName.getText().trim();
        String cardID = txtCardID.getText().trim();
        String email = txtEmail.getText().trim();
        
        if(!inputCheck.isInputLengthCorrect(login, 20, 6)){
            lblLoginWarning.setText("Login length incorrect!");
            correctInputs[0] = 0;
        }else if(isLoginInUse(login)){
            lblLoginWarning.setText("Login already in use!");
            correctInputs[0] = 0;
        }else{
            lblLoginWarning.setText(" ");
            correctInputs[0] = 1;
        }
        
        if(!inputCheck.isPasswordStrongEnough(password1)){
            lblPassword1Warning.setText("Only alphanumeric values between 8 to 20 characters!");
            correctInputs[1] = 0;
        }else{
            lblPassword1Warning.setText(" ");
            correctInputs[1] = 1;
        }
        
        if(!inputCheck.doPasswordsMatch(password1, password2)){
            lblPassword2Warning.setText("Passwords do not match!");
            correctInputs[2] = 0;
        }else{
            lblPassword2Warning.setText(" ");
            correctInputs[2] = 1;
        }
        
        if(!inputCheck.isInputLengthCorrect(firstName, 20, 1)){
            lblFirstNameWarning.setText("Incorrect length!");
            correctInputs[3] = 0;
        }else{
            lblFirstNameWarning.setText(" ");
            correctInputs[3] = 1;
        }
        
        if(!inputCheck.isInputLengthCorrect(lastName, 20, 1)){
            lblLastNameWarning.setText("Incorrect length!");
            correctInputs[4] = 0;
        }else{
            lblLastNameWarning.setText(" ");
            correctInputs[4] = 1;
        }
        
        if(!inputCheck.isInputLengthCorrect(cardID, 10, 10)){
            lblCardIDWarning.setText("Must be exactly 10 characters long!");
            correctInputs[5] = 0;
        }else if(isCardIDinUse(cardID)){
            lblCardIDWarning.setText("Card already in use!");
            correctInputs[5] = 0;
        }else{
            lblCardIDWarning.setText(" ");
            correctInputs[5] = 1;
        }
        
        if(!inputCheck.isEmailCorrect(email)){
            lblEmailWarning.setText("Incorrect email format!");
            correctInputs[6] = 0;
        }else if(inputCheck.isEmailInDatabase(email)){
            lblEmailWarning.setText("Email already in use!");
            correctInputs[6] = 0;
        }else{
            lblEmailWarning.setText(" ");
            correctInputs[6] = 1;
        }
        
        int sum = 0;
        for(int i : correctInputs){
            sum += i;
        }
        if(sum == 7){
            ConnectionProvider conn = new ConnectionProvider();
            int idAccount = conn.addNewAccount(login, password1);
            conn.addUserPersonal(idAccount, cardID, firstName, lastName, email);
            JOptionPane.showMessageDialog(null, "User " + firstName + " " + lastName + "\nwith '" + login + "' as login added!");
            this.dispose();
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void txtPassword2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassword2KeyTyped
        if(txtPassword2.getPassword().length >= 20){
            evt.consume();
        }
    }//GEN-LAST:event_txtPassword2KeyTyped

    private void txtFirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyTyped
        if(txtFirstName.getText().length() >= 20){
            evt.consume();
        }
    }//GEN-LAST:event_txtFirstNameKeyTyped

    private void txtLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyTyped
        if(txtLastName.getText().length() >= 20){
            evt.consume();
        }
    }//GEN-LAST:event_txtLastNameKeyTyped

    private void txtCardIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCardIDKeyTyped
        if(txtCardID.getText().length() >= 10){
            evt.consume();
        }
    }//GEN-LAST:event_txtCardIDKeyTyped

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        if(txtEmail.getText().length() >= 100){
            evt.consume();
        }
    }//GEN-LAST:event_txtEmailKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCardIDWarning;
    private javax.swing.JLabel lblEmailWarning;
    private javax.swing.JLabel lblFirstNameWarning;
    private javax.swing.JLabel lblLastNameWarning;
    private javax.swing.JLabel lblLoginWarning;
    private javax.swing.JLabel lblPassword1Warning;
    private javax.swing.JLabel lblPassword2Warning;
    private javax.swing.JTextField txtCardID;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JPasswordField txtPassword2;
    // End of variables declaration//GEN-END:variables
}
