/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.dialogs.NewCustomerDialog;
import gui.dialogs.NewShipperDialog;
import gui.dialogs.ArrivalOfGoodsDialog;
import gui.dialogs.ShipGoodsDialog;
import database.ConnectionProvider;
import gui.dialogs.NewSupplierDialog;
import inventorydatabase.Goods;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import inventorydatabase.Person;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Joseph
 */
public class MainForm extends javax.swing.JFrame {
    private int id;
    private Person person = null;
    private JFrame loginFrame;
    private List<Goods> goods = new ArrayList();
    /**
     * Creates new form MainForm
     */
    public MainForm(int id,JFrame loginFrame) {
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle("Stock organizer");
        this.id = id;
        setVisible(true);
        this.loginFrame = loginFrame;
        getPerson();
        if(!isUserInformationPresent()){
            JOptionPane.showMessageDialog(null, "Your account is to be empty. \nCall administrator now.", "Account error", JOptionPane.ERROR_MESSAGE);
            dispose();
            loginFrame.setVisible(true);
        }else{
            String fullName = person.getFirstName() + " " + person.getLastName();
            String cardID = person.getCardId();
            lblWelcomeUser.setText("Welcome " + fullName);
            lblCardID.setText("Card ID: " + cardID);
        }
        hideColumn(4);
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcomeUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGoods = new javax.swing.JTable();
        btnReceive = new javax.swing.JButton();
        btnShip = new javax.swing.JButton();
        lblCardID = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuAddShipper = new javax.swing.JMenuItem();
        menuAddCustomer = new javax.swing.JMenuItem();
        menuAddSupplier = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblWelcomeUser.setText("Welcome sign");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Stock");

        tableGoods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Code", "Quantity", "Price per unit", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableGoods);
        if (tableGoods.getColumnModel().getColumnCount() > 0) {
            tableGoods.getColumnModel().getColumn(0).setResizable(false);
            tableGoods.getColumnModel().getColumn(1).setResizable(false);
            tableGoods.getColumnModel().getColumn(2).setResizable(false);
            tableGoods.getColumnModel().getColumn(3).setResizable(false);
            tableGoods.getColumnModel().getColumn(4).setResizable(false);
        }

        btnReceive.setText("Receive");
        btnReceive.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiveActionPerformed(evt);
            }
        });

        btnShip.setText("Ship");
        btnShip.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShipActionPerformed(evt);
            }
        });

        lblCardID.setText("cardID");

        jMenu1.setText("File");

        menuAddShipper.setText("New Shipper");
        menuAddShipper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddShipperActionPerformed(evt);
            }
        });
        jMenu1.add(menuAddShipper);

        menuAddCustomer.setText("New Customer");
        menuAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddCustomerActionPerformed(evt);
            }
        });
        jMenu1.add(menuAddCustomer);

        menuAddSupplier.setText("New Supplier");
        menuAddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddSupplierActionPerformed(evt);
            }
        });
        jMenu1.add(menuAddSupplier);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");

        jMenuItem3.setText("jMenuItem3");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnShip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReceive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(lblCardID))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblWelcomeUser)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReceive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShip))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWelcomeUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCardID)))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(JOptionPane.showConfirmDialog(this, 
           "Are you sure you want to exit?", "Exit confirmation",
           JOptionPane.YES_NO_OPTION,
           JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiveActionPerformed
        ArrivalOfGoodsDialog recGoodsDia = new ArrivalOfGoodsDialog(this, true);
    }//GEN-LAST:event_btnReceiveActionPerformed

    private void btnShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShipActionPerformed
        ShipGoodsDialog shipGoodsDialog = new ShipGoodsDialog(this, true);
    }//GEN-LAST:event_btnShipActionPerformed

    private void menuAddShipperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddShipperActionPerformed
        NewShipperDialog newShipperDialog = new NewShipperDialog(this, true);
    }//GEN-LAST:event_menuAddShipperActionPerformed

    private void menuAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddCustomerActionPerformed
        NewCustomerDialog newCustomerDialog = new NewCustomerDialog(this, true);
    }//GEN-LAST:event_menuAddCustomerActionPerformed

    private void menuAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddSupplierActionPerformed
        NewSupplierDialog newSupplierDialog = new NewSupplierDialog(this, true);
    }//GEN-LAST:event_menuAddSupplierActionPerformed
    
    private void getPerson(){
        ConnectionProvider conn = new ConnectionProvider();
        person = conn.getPersonByID(id);
    }
    
    private boolean isUserInformationPresent(){
        int idAcc = person.getIdAcc();
        return idAcc == -1 ? false : true;
    }
    private void hideColumn(TableColumn tableColumn){
        tableColumn.setMinWidth(0);
        tableColumn.setMaxWidth(0);
        tableColumn.setWidth(0);
    }
    /*
    *   Fills table with goods from database
    */
    private void fillTable(){
        if(goods.isEmpty()){
            fillListWithGoods();
        }else{
            goods.removeAll(goods);
            fillListWithGoods();
        }
        
        DefaultTableModel model = (DefaultTableModel) tableGoods.getModel();

        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        
        for (Goods goods : goods) {
            Object[] o = new Object[5];
            o[0] = goods.getName();
            o[1] = goods.getCode();
            o[2] = goods.getQuantity();
            o[3] = goods.getPricePerUnit();
            o[4] = goods.getId();
            model.addRow(o);
        }
        
    }
    
    /*
    *   Fills atribute 'goods' with goods from database
    */
    private void fillListWithGoods(){
        ConnectionProvider conn = new ConnectionProvider();
        goods = conn.getGoods();
    }
    
    private void hideColumn(int columnIndex){
        TableColumn tableColumnID = tableGoods.getColumnModel().getColumn(columnIndex);
        hideColumn(tableColumnID);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReceive;
    private javax.swing.JButton btnShip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCardID;
    private javax.swing.JLabel lblWelcomeUser;
    private javax.swing.JMenuItem menuAddCustomer;
    private javax.swing.JMenuItem menuAddShipper;
    private javax.swing.JMenuItem menuAddSupplier;
    private javax.swing.JTable tableGoods;
    // End of variables declaration//GEN-END:variables
}
