CREATE DATABASE Inventory;
USE Inventory;

CREATE TABLE Accounts(
	id INT NOT NULL AUTO_INCREMENT,
	login VARCHAR(30) NOT NULL,
	password VARCHAR(100) NOT NULL,
	dateCreated DATE NOT NULL,
	lastPasswordChange DATE NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE UserPersonal(
	id INT NOT NULL AUTO_INCREMENT,
	idAccount INT NOT NULL,
	cardId VARCHAR(10) NOT NULL,
	firstName VARCHAR(50) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(idAccount) REFERENCES Accounts(id)
		ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE Addresses(
	id INT NOT NULL AUTO_INCREMENT,
	country VARCHAR(50) NOT NULL,
	countryState VARCHAR(30) NOT NULL,
	postalCode VARCHAR(10) NOT NULL,
	city VARCHAR(50) NOT NULL,
	street VARCHAR(50) NOT NULL,
	streetNum INT NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE Goods(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	code VARCHAR(50) NOT NULL,
	unit VARCHAR(30) NOT NULL,
	quantity INT NOT NULL,
	pricePerUnit FLOAT(10,2) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE Suppliers(
	id INT NOT NULL AUTO_INCREMENT,
	idAddress INT NOT NULL,
	name VARCHAR(30) NOT NULL,
	phone VARCHAR(20) NOT NULL,
	email VARCHAR(50) NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(idAddress) REFERENCES Addresses(id)
		ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE Customers(
	id INT NOT NULL AUTO_INCREMENT,
	idAddress INT NOT NULL,
	name VARCHAR(50) NOT NULL,
	phone VARCHAR(20) NOT NULL,
	email VARCHAR(50) NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(idAddress) REFERENCES Addresses(id)
		ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE Shippers(
	id INT NOT NULL AUTO_INCREMENT,
	idAddress INT NOT NULL,
	name VARCHAR(30) NOT NULL,
	phone VARCHAR(20) NOT NULL,
	email VARCHAR(50) NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(idAddress) REFERENCES Addresses(id)
		ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE Expeditions(
	id INT NOT NULL AUTO_INCREMENT,
	idCustomer INT NOT NULL,
	idShipper INT NOT NULL,
	idUser INT NOT NULL,
	expeditionDate DATE NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(idCustomer) REFERENCES Customers(id)
		ON DELETE CASCADE ON UPDATE RESTRICT,
	FOREIGN KEY(idShipper) REFERENCES Shippers(id)
		ON DELETE CASCADE ON UPDATE RESTRICT,
	FOREIGN KEY(idUser) REFERENCES UserPersonal(id)
		ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE ExpeditionDetails(
	id INT NOT NULL AUTO_INCREMENT,
	idExpedition INT NOT NULL,
	idGoods INT NOT NULL,
	quantity INT NOT NULL,
	expeditionDate DATE NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(idExpedition) REFERENCES Expeditions(id)
		ON DELETE CASCADE ON UPDATE RESTRICT,
	FOREIGN KEY(idGoods) REFERENCES Goods(id)
		ON DELETE CASCADE ON UPDATE RESTRICT
);



CREATE TABLE Arrivals(
	id INT NOT NULL AUTO_INCREMENT,
	idSupplier INT NOT NULL,
	idShipper INT NOT NULL,
	idUser INT NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(idSupplier) REFERENCES Suppliers(id)
		ON DELETE CASCADE ON UPDATE RESTRICT,
	FOREIGN KEY(idShipper) REFERENCES Shippers(id)
		ON DELETE CASCADE ON UPDATE RESTRICT,
	FOREIGN KEY(idUser) REFERENCES UserPersonal(id)
		ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE ArrivalDetails(
	id INT NOT NULL AUTO_INCREMENT,
	idArrival INT NOT NULL,
	idGoods INT NOT NULL,
	quantity INT NOT NULL,
	arrivalDate DATE NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(idArrival) REFERENCES Arrivals(id)
		ON DELETE CASCADE ON UPDATE RESTRICT,
	FOREIGN KEY(idGoods) REFERENCES Goods(id)
		ON DELETE CASCADE ON UPDATE RESTRICT
);




